name: clone workflow
on:
  workflow_dispatch:
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /pub/fbruce
            git clone git@github.com:chs-mix/cmsc389T-web-template.git 
