name: Update Workflow
on:
  push:

jobs:
  clone:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: update/ pulls from terpconnect 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ../pub/fbruce/cmsc389T-web-template
          git pull
